# Generated by Django 3.2 on 2022-06-07 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('cue', models.IntegerField(blank=True)),
                ('cuise', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=200)),
                ('dependencia', models.CharField(blank=True, max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('directivo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app001.directivo')),
                ('referente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Netbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(blank=True)),
                ('serie', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('imagen_win', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('estado_pila', models.CharField(choices=[('ok', 'ok'), ('agotada', 'agotada'), ('cambiada', 'cambiada')], default='agotada', max_length=20)),
                ('arranques', models.IntegerField(blank=True, default=0)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('sn', models.CharField(blank=True, max_length=30)),
                ('hid', models.CharField(blank=True, max_length=20)),
                ('boottick', models.CharField(blank=True, max_length=10)),
                ('estado_disco', models.CharField(choices=[('llevado', 'llevado'), ('flasheado', 'flasheado'), ('sin flashear', 'sin flashear')], default='sin flashear', max_length=20)),
                ('estado', models.CharField(choices=[('ok', 'ok'), ('no funciona', 'no funciona'), ('bloqueada', 'bloqueada'), ('pendiente de revision', 'pendiente de revision'), ('pendiente migracion', 'pendiente migracion'), ('robada', 'robada')], default='pendiente de revision', max_length=30)),
                ('detalle', models.TextField(blank=True)),
                ('imagen1', models.ImageField(blank=True, upload_to='netbooks')),
                ('escuela', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app001.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('detalle', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_actividad', models.CharField(choices=[('creacion', 'creación'), ('consulta', 'consulta'), ('modificacion', 'modificación'), ('eliminacion', 'eliminación')], max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
