# Generated by Django 3.2 on 2022-06-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='departamento',
        ),
    ]
