# Generated by Django 3.2 on 2022-06-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0002_remove_escuela_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='dependencia',
        ),
        migrations.AddField(
            model_name='escuela',
            name='departamento',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
