# Generated by Django 3.2 on 2022-07-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0004_alter_directivo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netbook',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('no funciona', 'no funciona'), ('bloqueada', 'bloqueada'), ('pendiente de revision', 'pendiente de revision'), ('pendiente migración', 'pendiente migración'), ('robada', 'robada')], default='pendiente de revision', max_length=30),
        ),
    ]
