# Generated by Django 3.2 on 2022-07-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0006_alter_netbook_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100),
            preserve_default=False,
        ),
    ]
