# Generated by Django 3.2 on 2022-07-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0007_informe_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='directivo',
        ),
        migrations.AddField(
            model_name='directivo',
            name='escuela',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='app001.escuela'),
            preserve_default=False,
        ),
    ]
